Var= input("Digite algo:")
print (" O tipo primitivo dessa variável é",type(Var))
print("sÓ TEM ESPAÇOS ?",Var.isspace())
print("É um número ? ", Var.isnumeric())
print("É alfabético ?",Var.isalpha())
print("É alfanumerico ?",Var.isalnum())
print("Está em maiusculo ?",Var.isupper())
print("Está em minusculo ?",Var.islower())
print("Está capitalizada?",Var.istitle())
